### ISSUE TITLE
Optional arg with default value

### ISSUE THREAD

**Issue by tuncer** [jcomellas/getopt#34]
This would be very useful:

```
$ cmd --opt
opt = true
```

```
$ cmd --opt one
opt = one
```

The default value shouldn't be limited to a boolean though.

**Comment by tuncer** [comment]
bump?

**Comment by jcomellas** [comment]
@tuncer I really don't have the bandwidth to add this feature at the moment. Feel free to send a PR with the needed changes if you want.

**Comment by tuncer** [comment]
It's not a pressing issue. Let's close it, then.
