### ISSUE TITLE
Hex.pm package takeover

### ISSUE THREAD

**Issue by drobakowski** [jcomellas/getopt#36]
@jcomellas I've seen that your library is published on `hex.pm` - https://hex.pm/packages/getopt. Would it be possible that you could takeover this package and make it a "official" one under your name? I think this could help to increase security and confidence in this package.

**Comment by jcomellas** [comment]
@drobakowski Yes, I was planning on doing that. It's just that I've been doing much more Elixir than Erlang programming lately. I will attempt the package takeover when I release the new version.

**Comment by jcomellas** [comment]
@drobakowski Sorry for the delay. I'm now owner of the `getopt` package and have published a new version of it.
