### ISSUE TITLE
Intended usage of binary arguments

### ISSUE THREAD

**Issue by sskorokhodov** [jcomellas/getopt#38]
What is the intended usage for arguments of `binary` type?

When one uses `getopt` to parse arguments of escript (which I think is the most popular scenario), Erlang provides arguments as (already decoded) strings containing integer code points.

Using `list_to_binary/1` to make binary from such a string

1. In the best case (when _no_ symbols >255 are present) gives latin-1 encoded binary. The binary represents initial argument from command-line. This binary can not be passed to functions from `string` module, because they expect binary strings to be normalized UTF-8 sequence.
2. In the worst case (when symbols >255 are present) the binary is neither what was passed as argument, nor a proper unicode sequence.

Also, default values for arguments of `binary` type are converted to strings using `binary_to_list/1`, producing invalid values for non-latin1 strings.

For our project which uses UTF-8 encoded binaries I patched `getopt` to add a new argument type `utf8`. Arguments of this type are encoded using `unicode:characters_to_binary/1`.

The other option is to use `file:native_name_encoding/0` to determine how argument should be encoded. This is obviously a breaking change.

The third option is to use `string` arguments instead of `binary` ones. This supposes manual encoding of each value to produce a binary string.

Please tell me if I misunderstood something.

**Comment by jcomellas** [comment]
The original support for binary arguments was to simplify the conversion for applications that were using those values as binaries. This project predates the existence of the `unicode` module in Erlang and has not been modified to use it for arguments yet.

BTW, I'm not sure there is a need to support anything other that UTF-8 strings. Do you see a need for explicit Latin-1 support? Also, I'm not sure that checking the result of `file:native_name_encoding/0` would be enough to determine what character set to use.

I'd appreciate if you could open a pull request with your changes.

**Comment by sskorokhodov** [comment]
Thank you for the clarification!

I'd prefer to stick with adding a new `utf8` type. It preserves compatibility and makes clear how parameter value is encoded. There is no special support for Latin-1 in this case, but `binary` type remains available for those who need it for some reason. I also want to add corresponding information to the README.

Is it ok? If so, I'll make a pull request ASAP.

**Comment by jcomellas** [comment]
Then what I think we should do is actually add two new options so that we provide UTF-8 encoded values that are similar to the preexisting string types:

  - `utf8_binary`
  - `utf8_string`

**Comment by sskorokhodov** [comment]
`utf8_string` will always be the original string passed to main as it happens with `string`. Code points for Latin-1 and Unicode are the same. Do you suggest adding `utf8_string` just for "symmetry"?

**Comment by sskorokhodov** [comment]
Resolved by fde61fe7
