### ISSUE TITLE
README says to use version 1.0.2 but in hex.pm 1.0.1 is the latest

### ISSUE THREAD

**Issue by aaronlelevier** [jcomellas/getopt#47]
Hi,

I tried following the README.md and couldn't install version 1.0.2, then I checked hex.pm and it says that 1.0.1 is the latest version of `getopt`.  Will you publish the 1.0.2 version to hex.pm soon?

Links:
- https://hex.pm/packages/getopt
- https://github.com/jcomellas/getopt/blob/master/README.md#installation

Output when installing:
```
===> Fetching getopt v1.0.1
===> Downloaded package, caching at /Users/aaron/.cache/rebar3/hex/hexpm/packages/getopt-1.0.1.tar
```

Thanks

**Comment by lukebakken** [comment]
@jcomellas I plan on releasing a new version of Cuttlefish and upgrading `getopt` to `1.0.2` via hex.pm would be great. Thanks.

https://github.com/Kyorai/cuttlefish/pull/8

**Comment by jcomellas** [comment]
@lukebakken Sorry for the delay, I've been swamped at work. I will deal with this between today and tomorrow.

**Comment by lukebakken** [comment]
Thank you so much!

**Comment by aaronlelevier** [comment]
Thank you

**Comment by michaelklishin** [comment]
[`1.0.1` is still the latest release published](https://hex.pm/packages/getopt).

**Comment by jcomellas** [comment]
I've already pushed version 1.0.2. Sorry for the delay, but I had an issue with the rebar3 hex plugin that took a while to resolve.
